# Generated by Django 4.2.23 on 2025-08-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flt_no', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=70)),
                ('sch_dep_dt', models.DateField(max_length=100)),
                ('sch_dep_tm', models.CharField(max_length=120)),
            ],
        ),
    ]
