# Generated by Django 4.2.23 on 2025-08-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uçuşlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flt_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='flight',
            name='sch_dep_tm',
            field=models.TimeField(max_length=120),
        ),
        migrations.AlterField(
            model_name='flight',
            name='sector',
            field=models.CharField(max_length=10),
        ),
    ]
